services:
  db:
    container_name: recruitmentDB
    image: postgres:16
    restart: unless-stopped

    environment:
      POSTGRES_USER: recruitment-user
      POSTGRES_PASSWORD: Ara_123 # ko hardcode password, change it in production
      POSTGRES_DB: recruitmentDB

    ports:
      - "5432:5432"
      
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: