"""Add user table and foreint key

Revision ID: c35f4cd7730b
Revises: 1558793daa58
Create Date: 2026-10-08 18:16:33.802747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c35f4cd7730b'
down_revision: Union[str, Sequence[str], None] = '1558793daa58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('jobdescrip', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'jobdescrip', 'user', ['user_id'], ['id'])
    op.add_column('resume', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'resume', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resume', type_='foreignkey')
    op.drop_column('resume', 'user_id')
    op.drop_constraint(None, 'jobdescrip', type_='foreignkey')
    op.drop_column('jobdescrip', 'user_id')
    op.drop_table('user')
    # ### end Alembic commands ###
